version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite://db.sqlite
    volumes:
      - .:/app
      - /app/node_modules