apiVersion: v1
kind: Service
metadata:
  name: edukita-backend-service
spec:
  selector:
    app: edukita-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer